#define DSTUFF_FILE_PATH_IMPLEMENTATION
#include "dstuff/file/path.h"
#define DSTUFF_FILE_FILE_IMPLEMENTATION
#include "dstuff/file/file.h"
#define DSTUFF_SPRITE_SPRPK_IMPLEMENTATION
#include "dstuff/sprite/sprpk.h"
#define STB_IMAGE_IMPLEMENTATION
#include "stb/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb/stb_image_write.h"
